### PR TITLE
New Features and using autopep8

### PR DESCRIPTION
**Pull request by jotyGill**
Hi There! 

Thanks again for all the work. I used python-autopep8 in Atom to auto format the code 59171b6cff227f67b285bbad1099d6c72fc47620 . I just found out about it, it's pretty cool. If you plan to work more on the project I recommend trying it out, so the code is always consistent. 

I have made the process of choosing the __basefilepath__ automatic (depending on the OS) 1900ae95fd84c0ddf571ad272955ca335f6792d2 . So if it's more convenient (probably is) we can change the __basefilepath__ for MacOS so users won't have to boot into recovery mode.
Let me know what location would work best.
 
I have also added some other things. 

Cheers :)

### CODE REVIEW

**Comment by 1951FDG** [comment]
Hi,

Nice! For MacOS we could use `/usr/local/share/openpyn/`

I also use Atom, great editor, regarding `python-autopep8`, why not use this newer repo, that has been updated more recently, [python-indent](https://atom.io/packages/python-indent)

There is also ide-python, which supports PyCodeStyle, now with maximum line length, default 79, but we could increase this, 79 is a bit short, considering the fact that we all use high res monitors, at least that's my opinion...

Thanks for making basefilepath dynamic!

**Comment by jotyGill** [comment]
Sounds good.

does python-indent auto formats code on save (changing inconsistent spaces, line lengths)?
with python 79 is too low, I keep (try to) it 100.

**Comment by 1951FDG** [comment]
python-indent does not, but found something better: https://atom.io/packages/atom-beautify

You can specify multiple settings including max line length and it can auto format the code on save like python-autopep8, 

screen shot 2018-02-04 at 21 55 39

**Comment by 1951FDG** [comment]
Did you have time to try , https://atom.io/packages/atom-beautify

**Comment by jotyGill** [comment]
Hey! Mate, I have been busy with some stuff, I am back again to work on the project. Yes I had atom-beautify installed, didn't know it has good support for python. Thanks for pointing out.

**Comment by 1951FDG** [comment]
Hey! Yeah it works fine, but I did not notice that autopep8 sometimes doesn't split lines when the max line length is exceeded, for example, initd.py @ https://github.com/1951FDG/openpyn-nordvpn/commit/59171b6cff227f67b285bbad1099d6c72fc47620

I've also setup the Preferred Line Length to match the Max line length. I also have warnings provided by https://atom.io/packages/ide-python, which help to make manual corrections. I hope this info helps others who will contribute in the future...

screen shot 2018-03-24 at 12 56 16

screen shot 2018-03-24 at 23 29 11

**Comment by 1951FDG** [comment]
So, another update, and I believe I'm done for now, I'v disabled all the linting done by https://atom.io/packages/ide-python and I'm using https://github.com/AtomLinter/linter-pylama now, tried other linters but like this one the best, at least for now...

```
pip3 install isort
pip3 install pylint
pip3 install pylama
pip3 install pylama-pylint
```

The isort sorting functionality built in to linter-pylama wasn't working for me, so I'm also using https://github.com/bh/atom-python-isort for sorting imports

I set `/usr/local/bin/python3` as the default interpreter and used a pylama custom config located in the root of the openpyn-nordvpn project, pylama.ini

contents of pylami.ini

```
[pylama]
linters = mccabe,pep8,pylint,isort

[pylama:mccabe]
complexity = 17

[pylama:pep8]
max_line_length = 125

[pylama:pylint]
max-line-length = 125
```

I also have a custom pylint configuration file, located in my home folder, '~/.pylintrc', which is read by pylama-pylint (default: /usr/local/lib/python3.6/site-packages/pylama_pylint/pylint.rc)

https://gist.github.com/1951FDG/37ce96a644e7b53b5ef0236650214b66

screen shot 2018-03-26 at 23 34 14

This is more or less a rather fine dev environment, for any anyone who wants to contribute to this project or any other Python project

screen shot 2018-03-26 at 23 27 39

**Pull request merged**
